# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LSILTy2BgXa-l_PsSGgrNpXSvOhJEe9p
"""

pip install wikipedia

pip install tkinter

from tkinter import *
from tkinter.messagebox import showinfo
import wikipedia

def question_answer:
  question=e1.get()
  answer=wikipedia.summary(question)
  showinfo("answer",answer)

root=Tk()
root.geometry("400x100")
question=StringVar()
e1=Entry(root,text_variable=question)
e1.grid(row=1,column=1,padx=20)

b1=Button(root,width=12,command=question_answer)
b1.grid(row=3,colums=2)

root.mainloop()

